# fly.toml app configuration file generated for bsk-feeds on 2023-08-07T11:46:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bsk-feeds"
primary_region = "lhr"

[build]

[env]
	FEEDGEN_PORT="3000"
	FEEDGEN_LISTENHOST="0.0.0.0"
	FEEDGEN_PUBLISHER_DID="did:plc:wlgerp2not5oct7twfq2teyg"
	FEEDGEN_SQLITE_LOCATION="/data/db.sqlite"
	FEEDGEN_HOSTNAME="bsky-feed.littlebonsai.co.uk"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
